name: 1-hour-cron-deploy
on:
  schedule:
    - cron: '* */1 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy hownoww.com
        run: |
          curl --request POST \
          --url 'https://api.vercel.com/v1/integrations/deploy/prj_ItEcG9v2G3CVgObAInE72f6CE6Ky/2XXKyd1Dzd' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
